#spring.application.name=tickets-vuelo

server:
  port: 0

spring:
  application:
    name: tickets-vuelo

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true